# Generated by Django 3.2.7 on 2021-09-24 02:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('fecha_publicacion', models.DateField()),
                ('video', models.FileField(upload_to='videos')),
                ('categoriaC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorialSLMApp.categoria')),
            ],
        ),
    ]
