# Generated by Django 3.2.7 on 2021-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialSLMApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='usuario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
