# Generated by Django 3.2.7 on 2021-09-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialSLMApp', '0003_auto_20210928_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoriaC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorialSLMApp.categoria'),
        ),
    ]
