# Generated by Django 3.2.7 on 2021-09-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialSLMApp', '0004_subcategoria_categoriac'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='sobre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
